### ISSUE TITLE
Error in sawfish discovery stage

### ISSUE THREAD

**Issue by zigge90** [PacificBiosciences/sawfish#4]
Hi!

I am using sawfish v.0.12.6 to identify SVs in my PacBio Hifi data that I have aligned to a reference genome using pbmm2.
However, I get the following error message for each of my 10 samples:

_[sawfish][ERROR] Diploid chromosome regex '^(chr)?\d{1,2}$' does not match any chromosome names in the input alignment file, use '--cov-regex "."' to match all available chromosomes._

I checked the headers of the fasta file and bam files and they look the same. Do you know what could be wrong? This is the code I used to discover SVs:

sawfish discover --threads 16 --ref mLynPar1.2.scaffolds.revcomp.scaffolds.fa --bam lp158.aln.hifi.bam --output-dir lp158_discover_dir

**Comment by ctsa** [comment]
Hi @zigge90 -

To solve this issue, the short answer is to add the following option to your discover cmdline: `--cov-regex "."` 

For a longer answer I can explain a little more about what's going on:

It's useful for us to be able to tell sawfish which chromosomes are the primary autosomal diploid chromosomes when it is being run for its most typical use cases, which include human, mouse, etc. Sawfish uses this information to estimate the mean haploid sequencing coverage, which can be used to improve genotyping accuracy. (I should note these improvements are incomplete -- several genome-wide depth capabilities are still being built into the model).

The default regular expression `^(chr)?\d{1,2}$` tells sawfish which diploid chromosomes to use for its depth estimation routine. In your case none of your scaffold names match this pattern, so it doesn't know how to proceed. Replacing this default with the regular expression `.` will match all chromosomes instead, so that all the routines can run to completion for any reference, with minimal (in fact at this point I think no) impact on SV call quality.

-Chris

**Comment by zigge90** [comment]
Thank you very much for explaining this, it makes perfect sense and the script is working fine after adding --cov-regex "."

Best wishes

**Comment by ctsa** [comment]
Thanks @zigge90, good to hear this.
