### ISSUE TITLE
somatic SV?

### ISSUE THREAD

**Issue by DayTimeMouse** [PacificBiosciences/sawfish#5]
Hi,

Does sawfish support to call somatic Svs in tumor/normal paired samples?

Best regards.

**Comment by ctsa** [comment]
Hi, We're not supporting somatic SV calling at this time. For the latest recommended HiFi somatic workflow, please see:

https://github.com/PacificBiosciences/HiFi-somatic-WDL

You can either use this workflow in whole or look to this workflow for updates on recommended components. I believe the recommended somatic SV caller in the workflow at this time is Severus.

**Comment by ajw2329** [comment]
@ctsa  quick followup question on this topic:

do you think sawfish is not likely to find somatic SVs in the first place, or is it just the case that sawfish doesn't have the tooling to help discriminate between germline/somatic events?

I'm asking because sawfish does seem to report lower VAF events (e.g. `GT:GQ:PL:AD   0/0:38:0,38,999:44,2`) -- when I see these I wonder if they are somatic mosacisms.

Thanks and thanks for the great tool!

**Comment by ctsa** [comment]
At this time the lack of any sample subtraction logic to distinguish germline from somatic is probably one of the biggest missing capabilities for somatic calling.

For mosaic calls in general, I imagine sawfish would be okay but haven't done any systematic testing. The genotyping model would really benefit from some customization to allow for the mosaic case though, especially if you were trying to get to lower frequencies at higher sequencing coverage.
